### ISSUE TITLE
grader message shows up when it shouldn't

### ISSUE THREAD

**Issue by DanJFletcher** [DanJFletcher/khan-grouped-animals#2]
## Trigger

``` css
           h1, h2{
                font-family: fantasy;
                border-bottom: 1px solid rgb(230, 230, 230);
                padding: 3px;
            }

            h1:hover, {
                background-color: rgb(248, 255, 199);
            }
```

The code above triggers the message:

> Remember: when you're grouping selectors with ':hover', make sure that you put ':hover' after each selector that you group.

When in fact, there is no reason for this message; the student is doing everything correct.
